jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - name: access to secrets
        run: |
          echo "MAP_API_KEY=$MAP_API_KEY" >> .env
        env:
          TOKEN: ${{secrets.TOKEN}}
          ID: ${{secrets.ID}}
          CHATGPTKEY: ${{secrets.CHATGPTKEY}}
